### ISSUE TITLE
Implementación del API/WeatherLeftCard

### ISSUE THREAD

**Issue by JosuePlataV** [araceli4920/requisitos-segundo-parcial#15]
El equipo de desarrollo de esta página, basados en la información investigada previamente mediante la realización del issue de planeación, se implementarán los datos mencionados en el issue “Diseño/WeatherLeftCard” a través del API de clima de OpenWeather:
- [x] Introducir en la card superior izquierda Clima actual (de la ciudad que el usuario elija)
- [x] Introducir en la card superior izquierda fecha actual
- [x] Introducir en la card superior izquierda ubicación
- [x] Introducir en la card inferior izquierda el clima de los siguientes días (el máximo de días permitido por la versión gratis del API)

**Comment by araceli4920** [comment]
Marcar actividades realizadas por cada uno de sus issues correspondientes para saber cuales quedan pendientes.
