### ISSUE TITLE
Actividades 1 

### ISSUE THREAD

**Issue by MacRoberto** [araceli4920/requisitos-segundo-parcial#2]
- [x] Asegurarse de que tengan Github Desktop instalados en sus equipos.
- [x] #13
- [x] Crear un grupo en Whatsapp para coordinación.
- [x] #34
- [x] Avanzar en su auto formación en uso de "Visual Estudio Code" (Ver tutoriales, leer o analizar libro de "Visual Studio Code de Bruce Jhonson, ...,).
- [ ]  Hacer la documentación del proyecto.
- [x] Estar monitoriando los issues que serán publicados proximamente según las necesidades o requerimientos del proyecto en desarrollo.

**Comment by araceli4920** [comment]
se va a realizar la investigacion, para llevar a cabo la documentacion del proyecto. estar pendientes. fecha compromiso: 25/6/24

**Comment by araceli4920** [comment]
modificar las instrucciones y quitar de la lista los requerimientos que indico el cliente (profesor) no son necesarios.

**Comment by MacRoberto** [comment]
Documentación pendiente.
