### ISSUE TITLE
Página API Weather/Responsivo

### ISSUE THREAD

**Issue by JosuePlataV** [araceli4920/requisitos-segundo-parcial#21]
El profesor junto al equipo de desarrollo de todo el proyecto determinó que todas las páginas dentro del mismo debían ser responsivas. 

- [x] Se agregó el responsivo de móvil
- [x] Se agregó el responsivo de tablet
- [x] Se agregó el responsivo de escritorio (computadoras)

**Comment by TilinMamarre69** [comment]
He completado el responsivo de la página `weather.html`.

**Comment by TilinMamarre69** [comment]
Todo funciona correctamente como se muestra en el commit realizado hace unas horas por lo que procederé a cerrar este issue.
