### ISSUE TITLE
Página Principal Home(index)/Responsivo

### ISSUE THREAD

**Issue by JosuePlataV** [araceli4920/requisitos-segundo-parcial#22]
El profesor junto al equipo de desarrollo de todo el proyecto determinó que todas las páginas dentro del mismo debían ser responsivas. 

- [x] Se agregó el responsivo de móvil
- [x] Se agregó el responsivo de tablet
- [x] Se agregó el responsivo de escritorio (computadoras)

**Comment by TilinMamarre69** [comment]
Se ha hecho el diseño final de la página principal y el responsivo de la misma.
