### ISSUE TITLE
Revisar codigo de "random user generator"

### ISSUE THREAD

**Issue by MacRoberto** [araceli4920/requisitos-segundo-parcial#28]
Como miembro del equipo desarollador de la pagina de Random user generator se hace una propuesta de la pagina; la cual es necesario:

- [x] Hacer un revisión de las lineas de código.
- [x] Realizar propuestas de cambio.
- [x] Agregar los datos que faltan de los usuarios. (Arturo).

**Comment by araceli4920** [comment]
se realizo la revision de codigo y diseño.. Falta añadir los sigientes datos de usuario siguiendo el modelo que se nos envio por el grupo de whatsapp (direccion y fecha de cumpleaños) pendientes para mostrar en informacion de usuario.

**Comment by araceli4920** [comment]
subir todos los cambios y procesos del proyecto para poder realizar la documentacion mas extensa.
