### ISSUE TITLE
Creación de archivos, Estructura html

### ISSUE THREAD

**Issue by Scar269** [araceli4920/requisitos-segundo-parcial#6]
Como equipo de desarrollo es necesario que la información básica de la api se conecte y se muestre en un **archivo html,** con la ayuda de otro archivo js, y el archivo de estilos, para empezar a hacer la página principal del proyecto 

- [x] Crear la estructura de carpetas y archivos iniciales para el proyecto: index.html, styles.css, app.js

Estructura html
- [x] Vincular le archivo de estilos css mediante un link
- [x] Agregar un div
- [x] Dentro del div agregar imagen
- [x] Dentro de otro div agregar un H1
- [x] agregar la cantidad de párrafos según la información que sea agregada
- [x] Vincular el archivo JSON mediante un script

*No olvidar dejar el espacio al final de cada archivo html

**Comment by araceli4920** [comment]
realizar revision e ir marcando las actividades realizadas.

**Comment by Luzclarita18** [comment]
Actividad realizada solo necesito que lo revisen ya que hice un pull  requests @araceli4920 @Scar269
